# fly.toml file generated for rsx-bot on 2022-08-31T19:49:42-05:00

app = "rsx-bot"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builtin = "node"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]

[mounts]
  source="rsx_bot_db"
  destination="/mnt/rsx_bot_db"